#parameter for histogram plot
#Path of the data
ADCP_FILE_NAME_UP:   'ADCPDATA/MUO2_UP_2023-11-21_to_2024-03-06.23656'
ADCP_FILE_NAME_DOWN: 'ADCPDATA/MUO2_DOWN_2023-11-21_to_2024-03-06.38100'
#Discharge file name
FILE_DISCH: 'DATADISCHMETEO/Discharge_June_Dec2023_NEW.txt'
#METO FILE
FILE_METEO: 'DATADISCHMETEO/DATA_ARRANGE_ALT.csv'
#FILE_METEO: 'DATASELECT/DATA_ARRANGE_GES.csv'
#Temperature file
FILE_TEMPE: 'DATADISCHMETEO/DataTemperatureMooringA.json'
#Seimic file
#mseedFile: 'DATASELECT/STATION03/XJ_MUS03_HH1-2023-08-28.mseed'
#
ADCP_DOWN: False
############################
PLOT2ADCP: True
#Plot Options 
#Mooring B
#Set the SEAFLOOR DEPTH at the location of the ADCP
SEAFLOOR_DEPTH: 120.0 # in meter
#Set the ADCP DEPTH
ADCP_UP_HEIGTH_FROM_LAKEBED: 20.9    #depth above the sediment in meter
ADCP_DOWN_HEIGTH_FROM_LAKEBED: 20.0  #depth above the sediment in meter
#
Remove_frame: True
#DO you want to visualize the data parameters? if yes set to True if no set to False
##Set the time in the following format YYYY-MM-DD 
#STARTDATE: "2023-08-29"
#####Set the ending time
#ENDDATE: "2023-11-02"
#Make your plot bigger
plot_bigger: True
#Parameter to plot Horizontal velocity, this actually the Horizontal velocty
velocity_up: False
velocity_down: False
#Parameter to plot Horizontal velocity Direction in degrees clockwise from North: degrees_CW_from_N 
veldir2D_up: False
veldir2D_down: False
#################### #
veldir1D_up: False
veldir1D_down: False
#Parameter to plot Vertical  Velocity, this actually the Vertical velocty given the componant w
vertical_vel_up: False
vertical_vel_down: False
#Do want to plot water Pressure?
pressure_up: False
pressure_down: False
###########
surface_tracking_up: False
surface_tracking_down: False
#Plot the depth change of ADCP
depth_adcp_up: False
depth_adcp_down: False
#Plot Particle motions in the water column
pm_adcp_up: True
pm_adcp_down: True
#############################
hist_adcp_up: False
hist_adcp_down: False
#Plot Particle motions in the water column
pm3D_adcp_up: False
pm3D_adcp_down: False
##1D Current profile 
Current_Profile_up: False
Current_Profile_down: False
#Do want to plot Atmospheric Pressure?
Atm_pressure_QFE: False     # which is the pressure measure at the station
Atm_pressure_QFF: False   # Mean pressure at the sea level by taking into account the actual Temperature
#Do want to plot water Temperature?
temperature_up: False
temperature_down: False
Temperature2D: False
#Do want to plot the Dischage into the basin ?
discharge: False
#Do want to plot the 1D average Backscatter <====> Turbidity into the basin ?
avg_BS_up: False
avg_BS_down: False
#Do you want to plot the 2D backscatter
backscatter_up: False
backscatter_down: False
#Do you want to plot the 2D Velocity
velocity2D_up: False
velocity2D_down: False
#Do you want to plot the 1D Velocity Profile
velocity_profile_up: False
velocity_profile_down: False
#num_range control the turbidity and the 2Dvelocity plot 
#There is 25 ranges in generaly
num_range: 25
#num_range: 20
#Do want to plot the Turbidity Kenetic Energy ?
tke: False
#Wind speed
wind_speed: False
#Plot wind direction?
wind_direction : False
#Precipitation
precipitation: False
#plot the seismogram 
waveform: False
#Envelop 
envelope: False
#plot the seismic spectrogram?
spectrogram: False
#Do want to plot water density ?
#density: False
#DO you want to visualize the data correlation with depth (the quality of the data with depth)? if yes set to True if no set to False
#Ensemble Interval (s) = "600.00"
#To average the data into time bins, we need the parmeter below
#1) n_bin which represents the number of data points in each ensemble, 
#2) here our enseblme happen every 600s and  the frequency is fs = 0.001668, so n_bin = fs* 600 = 1
n_bin: 1
#Provido the beam number on which you want to visualize the data correlation
#Set the space between the figures
fig_space: 0.05
#fig_space: 0.25
#set the figure size
fig_width: 12
fig_height: 11
#Set the bandpass
#Good Frequency STATION03
bandpass: '0.02-0.022-200-1000'
#Just removed instrument response
bandpass_spec: '0.02-0.022-200-1000'
######################
#Dictionary for parameter to plot
PARAMSDICT: {'envelope':['Spectral Envelope (m/s²)','m'],  'waveform': ['Acceleration (µm/s²)','k'], 'spectrogram': ['Frequency [Hz]','jet'], 'hist_adcp_up':['Velocity occurrences','r'],'hist_adcp_down':['Velocity occurrences','r'], 'avg_BS_up': ['1D-Backscatter', 'green'], 'avg_BS_down': ['1D-Backscatter', 'blue'], 'backscatter_up': ['Backscattering', 'jet'] , 'backscatter_down': ['Backscattering', 'jet'] ,'velocity_up': ['Velocity (m/s)', 'k'], 'velocity_down': ['Velocity (m/s)', 'blue'],'veldir2D_up': ['degrees_CW_from_N', 'CMRmap'], 'veldir2D_down': ['degrees_CW_from_N', 'CMRmap'], 'veldir1D_up': ['degrees_CW_from_N', 'y'], 'veldir1D_down': ['degrees_CW_from_N', 'y'],'vertical_vel_up': ['Velocity (m/s)', 'c'], 'vertical_vel_down': ['Velocity (m/s)', 'c'],'velocity2D_up': ['Velocity (m/s)', 'jet'], 'velocity2D_down': ['Velocity (m/s)', 'jet'], 'velocity_profile_up': ['Velocity (cm/s)', 'k'], 'velocity_profile_down': ['Velocity (cm/s)', 'k'], 'Current_Profile_up': ['Vector position', 'b'],'Current_Profile_down': ['Vector position', 'b'],  'temperature_up': ['Temperature (°C)', 'r'], 'temperature_down': ['Temperature (°C)', 'r'],'Temperature2D': ['Temperature (°C)', 'jet'], 'pressure_up':['Pressure (bar)','tab:blue'], 'pressure_down':['Pressure (bar)','blue'], 'depth_adcp_up': [ 'Depth Variation (m)', 'teal'],  'depth_adcp_down': [ 'Depth Variation (m)', 'b'], 'pm_adcp_up':['Height above lakebed (m)', 'b'] , 'pm_adcp_down':['Height above lakebed (m)', 'b'], 'pm3D_adcp_up': ['range (m)', 'b'], 'pm3D_adcp_down': ['range (m)', 'b'],  'surface_tracking_up': ['Surface Track (m)', 'b'], 'surface_tracking_down': ['Bottom Track (m)', 'b'],   'tke': ['TKE (J/Kg)', 'pink'], 'discharge': ['Discharge (m³/s)','blueviolet'],'wind_speed':['W_speed (km/h)', 'teal'], 'wind_direction':['Wind-Dir (°C)', 'k'],'Atm_pressure_QFE': ['Atm_Pressure (bar)','seagreen'],  'Atm_pressure_QFF': ['Atm_Pressure (bar)','royalblue'], 
'precipitation': ['Precipitation (mm)','blue']}
